run:
  timeout: 5m
  go: "1.23"
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  govet:
    check-shadowing: true
    enable-all: true
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: webextractor
  gofmt:
    simplify: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  funlen:
    lines: 80
    statements: 40
  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK
  errorlint:
    errorf: true
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
  forbidigo:
    forbid:
      - ^print.*$
      - 'fmt\.Print.*'
  revive:
    min-confidence: 0
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]

linters:
  disable-all: true
  enable:
    # Erreurs
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Style
    - gofmt
    - goimports
    - revive
    - misspell

    # Complexité
    - gocyclo
    - funlen
    - gocognit

    # Performance
    - prealloc

    # Bugs
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - errorlint
    - exhaustive

    # Sécurité
    - gosec

    # Tests
    - testpackage

    # Autres
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - godox
    - goconst
    - gocritic
    - forbidigo

issues:
  exclude-rules:
    # Exclure certains linters pour les tests
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen

    # Exclure les erreurs G404 (faible générateur aléatoire) pour les tests
    - path: _test\.go
      text: "G404:"
      linters:
        - gosec

    # Permettre les prints dans main.go pour l'output CLI
    - path: main\.go
      linters:
        - forbidigo

    # Permettre les prints dans les packages d'output
    - path: internal/io/
      linters:
        - forbidigo

  # Nombre maximum de problèmes à afficher (0 = unlimited)
  max-issues-per-linter: 0
  max-same-issues: 0

  # Nouveaux problèmes uniquement
  new: false

  # Afficher les statistiques par linter
  print-stats: true
